services:
  openvpn:
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - MKNOD
      - SYS_MODULE
    image: kylemanna/openvpn
    ports:
      - "1194:1194/udp"
    restart: always
    volumes:
      - ./openvpn-data/conf:/etc/openvpn
      - /lib/modules:/lib/modules:ro
    devices:
      - /dev/net/tun
    privileged: true

  frpc:
    image: snowdreamtech/frpc:0.65
    volumes:
      - ./frpc/frpc.toml:/etc/frp/frpc.toml:ro
    restart: unless-stopped
    env_file: .env
